AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation creating ecs-updater lambda function, roles and permissions
Parameters:
  LambdaFunctionName:
    Type: String
    Default: ecs-updater
    Description: Name for ecs-updater lambda function
Resources:
  LambdaECSUpdater:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Handler: lambda-ecs-updater.lambda_handler
      Runtime: python3.9
      ReservedConcurrentExecutions: 1
      Code:
        ZipFile: |
          import json
          def handler(event, context) :
            print("Event: %s" % json.dumps(event))
      Role: !GetAtt
        - RoleLambdaECSUpdater
        - Arn
      Timeout: '30'
    DependsOn:
      - RoleLambdaECSUpdater
  RoleLambdaECSUpdater:
    Type: 'AWS::IAM::Role'
    Properties:
      Policies:
        - PolicyName: Custom-PolicyLambdaECSUpdater
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - 'ecs:UpdateService'
                  - 'ecs:RegisterTaskDefinition'
                  - 'ecs:DescribeServices'
                  - 'ecs:DescribeTaskDefinition'
                  - 'ecs:UntagResource'
                  - 'ecs:TagResource'
                  - 'tag:UntagResources'
                  - 'tag:TagResources'
                Resource:
                  - "*"
                Effect: Allow
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
Outputs:
  LambdaECSUpdaterArn:
    Description: Lambda ECS Scanner Arn
    Value: !GetAtt
      - LambdaECSUpdater
      - Arn
  LambdaECSUpdaterName:
    Description: Lambda ECS Scanner Name
    Value: !Ref LambdaFunctionName
